targets:
  $default:
    builders:
      drift_dev:
        options:
          scoped_dart_components: true

      riverpod_generator:
        options:
          provider_name_prefix: ""
          provider_family_name_prefix: ""
